name: OnlineFix Discord Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GH_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py

      - name: Guardar último post
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add last_post.txt
          git diff --cached --quiet || git commit -m "Actualizar último post"
          git push